// app/layout.tsx

import "./globals.css";
import React from "react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import type { Metadata } from "next";
import NavbarItems  from "@/app/components/Navbar"



export const metadata = {
  title: "Couleur Concept",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
